name: CI

on:
    push:
    pull_request:

jobs:
  phpstan:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          
      - name: Install composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
        
      - name: Clear Cache
        run: bin/console cache:clear --env=test
      
      - name: Run phpstan
        run: vendor/bin/phpstan --error-format=github
